### ISSUE TITLE
API not working with deploy on Heroku

### ISSUE THREAD

**Issue by badalpub1991** [devslopes-learn/mac-chat-api#19]
I have already successfully deployed api on heroku but i am not able to get response from heroku in application. I am getting this type of response when i am trying to register user.

`      po response.result.value
       ▿ Optional<String>
       - some : "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-
        8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST 
        /account/register</pre>\n</body>\n</html>\n"`

Help me with this issue please .

**Comment by ghost** [comment]
I would suggest checking out our apple slope, we walk you through all the steps in using this api.
