### ISSUE TITLE
error in npm run dev

### ISSUE THREAD

**Issue by pr656d** [devslopes-learn/mac-chat-api#22]
`> slacky-slack@1.0.0 dev C:\prem\work\DataBase\mac-chat-api`
`> NODE_ENV=development nodemon -w src --exec "babel-node src --presets es2015,stage-0"`

`'NODE_ENV' is not recognized as an internal or external command,`
`operable program or batch file.`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! slacky-slack@1.0.0 dev:` `NODE_ENV=development nodemon -w src --exec "babel-node src --presets es2015,stage-0"`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the slacky-slack@1.0.0 dev script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\myUserName\AppData\Roaming\npm-cache\_logs\2018-04-13T20_21_07_648Z-debug.log`

**Comment by maks-novikov** [comment]
Have same problem here, how you solved it?

**Comment by TromyTrain** [comment]
Did anyone find the answer, to solve this
Plz text as soon as possible

**Comment by arjavpatni** [comment]
I have got the same error. Please help if you solved it! @pr656d

**Comment by TromyTrain** [comment]
Yea sure,

You must put the Mac-chat-api file in the desktop and then try to connect
it with the file . If it again shows some error then send me the screen
shot of the error.

**Comment by arjavpatni** [comment]
Here is the solution,
Gotta update your mongodb package version in package.json
"mongoose": "5.8.3",
"passport-local-mongoose": "5.0.0",
"mongodb-core": "3.2.7"

Also remember to add this IP config network access on your Mongo DB Atlas: "0.0.0.0/0".
No unique character (#,%...) on your account password for access database
Deploy again, and it will work correctly.

**Comment by TromyTrain** [comment]
👍.
